### ISSUE TITLE
Deploy app to the virtual environment (Binder, Colab)

### ISSUE THREAD

**Issue by quantum-entangled** [quantum-entangled/gam-ml-test#11]
Set up the virtual environment for the global usage.

**Comment by CKPEIIKA** [comment]
what about in first place using some local virtual environment, e.g. conda? or it is planned to use docker for deployment (may be mild overkill for the python-only project)?

**Comment by quantum-entangled** [comment]
Yes, I'm actually using the built-in venv for development, conda is fine too. It doesn't actually matter for now which one to use, besides setting the proper Python version (3.10 for now) and install all libraries via requirements.txt. The main purpose of Docker, however, is, firstly, to unify the local development and web deployment environments (cause, e.g., Binder supports custom Dockerfiles), and secondly, to minimize the amount of recourses to set up before running the app. Moreover, Dockerfile has been already written in the previous version, it just needs to be tweaked a little bit for the current one.

**Comment by CKPEIIKA** [comment]
Its not urgent for now but later everything will be inevitable bound to specific versions of packages and some exact versions should be specified in requirements.txt.

**Comment by quantum-entangled** [comment]
Sure, we will stick to specific versions later and will be consequentially updating it if needed, for now it's just the latest.
